CRITICAL - 2021-08-01 20:33:33,257 - __main__ - restore.main - MainThread - Exception TypeError with message "_check_files() takes 1 positional argument but 2 were given" is not caught in /Users/rkrivov/PycharmProjects/s3_upload/restore.py:87
WARNING - 2021-08-01 20:51:42,384 - __main__ - restore.main - MainThread - User terminate program! in /Users/rkrivov/PycharmProjects/s3_upload/restore.py:85
CRITICAL - 2021-08-01 21:03:56,304 - __main__ - restore.main - MainThread - Exception AttributeError with message "'list' object has no attribute 'setdefault'" is not caught in /Users/rkrivov/PycharmProjects/s3_upload/restore.py:87
CRITICAL - 2021-08-01 21:04:57,111 - __main__ - restore.main - MainThread - Exception AttributeError with message "'list' object has no attribute 'setdefault'" is not caught in /Users/rkrivov/PycharmProjects/s3_upload/restore.py:87
CRITICAL - 2021-08-01 21:06:35,813 - __main__ - restore.main - MainThread - Exception AttributeError with message "'list' object has no attribute 'setdefault'" is not caught in /Users/rkrivov/PycharmProjects/s3_upload/restore.py:87
WARNING - 2021-08-01 21:07:09,698 - __main__ - restore.main - MainThread - User terminate program! in /Users/rkrivov/PycharmProjects/s3_upload/restore.py:80
WARNING - 2021-08-01 21:07:54,120 - __main__ - restore.main - MainThread - User terminate program! in /Users/rkrivov/PycharmProjects/s3_upload/restore.py:80
WARNING - 2021-08-01 21:08:33,049 - __main__ - restore.main - MainThread - User terminate program! in /Users/rkrivov/PycharmProjects/s3_upload/restore.py:80
CRITICAL - 2021-08-01 21:13:41,100 - __main__ - restore.main - MainThread - Exception TypeError with message "__init__() got an unexpected keyword argument 'dect'" is not caught in /Users/rkrivov/PycharmProjects/s3_upload/restore.py:82
CRITICAL - 2021-08-01 21:14:13,016 - __main__ - restore.main - MainThread - Exception TypeError with message "__init__() got an unexpected keyword argument 'dect'" is not caught in /Users/rkrivov/PycharmProjects/s3_upload/restore.py:76
CRITICAL - 2021-08-01 21:15:01,687 - __main__ - restore.main - MainThread - Exception ValueError with message "too many values to unpack (expected 2)" is not caught in /Users/rkrivov/PycharmProjects/s3_upload/restore.py:77
WARNING - 2021-08-01 21:19:17,909 - __main__ - restore.main - MainThread - User terminate program! in /Users/rkrivov/PycharmProjects/s3_upload/restore.py:72
CRITICAL - 2021-08-01 21:19:56,023 - __main__ - restore.main - MainThread - Exception AttributeError with message "'list' object has no attribute 'items'" is not caught in /Users/rkrivov/PycharmProjects/s3_upload/restore.py:77
WARNING - 2021-08-01 21:22:50,044 - __main__ - restore.main - MainThread - User terminate program! in /Users/rkrivov/PycharmProjects/s3_upload/restore.py:72
CRITICAL - 2021-08-01 21:24:07,951 - __main__ - restore.main - MainThread - Exception AttributeError with message "'str' object has no attribute 'startwith'" is not caught in /Users/rkrivov/PycharmProjects/s3_upload/restore.py:77
CRITICAL - 2021-08-01 21:35:18,341 - __main__ - restore.main - MainThread - Exception FileNotFoundError with message "[Errno 2] No such file or directory: '/Users/rkrivov/Parallels/Windows 10.pvm/Windows 10.app/Contents/Info.plist.6c0c796a'" is not caught in /Users/rkrivov/PycharmProjects/s3_upload/restore.py:77
WARNING - 2021-08-01 21:37:44,457 - __main__ - restore.main - MainThread - User terminate program! in /Users/rkrivov/PycharmProjects/s3_upload/restore.py:72
WARNING - 2021-08-01 23:54:25,519 - __main__ - restore.main - MainThread - User terminate program! in /Users/rkrivov/PycharmProjects/s3_upload/restore.py:76
WARNING - 2021-08-01 23:58:38,329 - __main__ - parallels.main - MainThread - User terminate program! in /Users/rkrivov/PycharmProjects/s3_upload/parallels.py:135
WARNING - 2021-08-01 23:58:43,468 - __main__ - restore.main - MainThread - User terminate program! in /Users/rkrivov/PycharmProjects/s3_upload/restore.py:72
WARNING - 2021-08-01 23:58:43,525 - __main__ - parallels.main - MainThread - User terminate program! in /Users/rkrivov/PycharmProjects/s3_upload/parallels.py:142
WARNING - 2021-08-02 09:44:50,386 - __main__ - parallels.main - MainThread - User terminate program! in /Users/rkrivov/PycharmProjects/s3_upload/parallels.py:142
WARNING - 2021-08-02 09:45:51,423 - __main__ - parallels.main - MainThread - User terminate program! in /Users/rkrivov/PycharmProjects/s3_upload/parallels.py:135
WARNING - 2021-08-02 09:46:43,854 - __main__ - parallels.main - MainThread - User terminate program! in /Users/rkrivov/PycharmProjects/s3_upload/parallels.py:142
WARNING - 2021-08-02 09:51:05,117 - s3.base - base._compare_files - MainThread - The file [0;37m[4m/Users/rkrivov/Parallels/Windows 10.pvm/VmInfo.pvi[4m[0;39m was changed: The size of the remote file ([0;36m[1m33.16 KB[22m[0;39m) differs from the size of the local file ([0;36m[1m32.43 KB[22m[0;39m), and the time when the remote file was last modified ([0;36m[1m2021-08-01 09:06:20[22m[0;39m) differs from the time when the local file was last modified ([0;36m[1m2021-08-02 06:50:23[22m[0;39m), and the ETag of the remote file ([0;36m[1md47360d33e4969e12da8c91b7ec7536a[22m[0;39m) differs from the ETag of the local file ([0;36m[1mf37f51bca917f2f7a2c793a0359b4cf7[22m[0;39m) in /Users/rkrivov/PycharmProjects/s3_upload/s3/base.py:263
WARNING - 2021-08-02 09:51:13,468 - s3.base - base._compare_files - MainThread - The file [0;37m[4m/Users/rkrivov/Parallels/Windows 10.pvm/config.pvs[4m[0;39m was changed: The size of the remote file ([0;36m[1m33.18 KB[22m[0;39m) differs from the size of the local file ([0;36m[1m33.10 KB[22m[0;39m), and the time when the remote file was last modified ([0;36m[1m2021-08-01 14:20:07[22m[0;39m) differs from the time when the local file was last modified ([0;36m[1m2021-08-02 06:50:23[22m[0;39m), and the ETag of the remote file ([0;36m[1m9a753aa8d0198ffc9a7b188ceea21841[22m[0;39m) differs from the ETag of the local file ([0;36m[1m7809c5caaee28288582c01fa1deb4035[22m[0;39m) in /Users/rkrivov/PycharmProjects/s3_upload/s3/base.py:263
WARNING - 2021-08-02 09:51:13,485 - s3.base - base._compare_files - MainThread - The file [0;37m[4m/Users/rkrivov/Parallels/Windows 10.pvm/statistic.log[4m[0;39m was changed: The size of the remote file ([0;36m[1m3.70 MB[22m[0;39m) differs from the size of the local file ([0;36m[1m3.70 MB[22m[0;39m), and the time when the remote file was last modified ([0;36m[1m2021-08-01 14:20:07[22m[0;39m) differs from the time when the local file was last modified ([0;36m[1m2021-08-02 06:50:24[22m[0;39m), and the ETag of the remote file ([0;36m[1me41f200834af85a34df13f5eeb02b678[22m[0;39m) differs from the ETag of the local file ([0;36m[1m9cc3e03874af7fd107dca3e9c270e9b3[22m[0;39m) in /Users/rkrivov/PycharmProjects/s3_upload/s3/base.py:263
WARNING - 2021-08-02 09:51:13,487 - s3.base - base._compare_files - MainThread - The file [0;37m[4m/Users/rkrivov/Parallels/Windows 10.pvm/config.pvs.backup[4m[0;39m was changed: The size of the remote file ([0;36m[1m33.18 KB[22m[0;39m) differs from the size of the local file ([0;36m[1m33.10 KB[22m[0;39m), and the time when the remote file was last modified ([0;36m[1m2021-08-01 14:20:07[22m[0;39m) differs from the time when the local file was last modified ([0;36m[1m2021-08-02 06:50:23[22m[0;39m), and the ETag of the remote file ([0;36m[1m9a753aa8d0198ffc9a7b188ceea21841[22m[0;39m) differs from the ETag of the local file ([0;36m[1m7809c5caaee28288582c01fa1deb4035[22m[0;39m) in /Users/rkrivov/PycharmProjects/s3_upload/s3/base.py:263
WARNING - 2021-08-02 09:51:13,524 - s3.base - base._compare_files - MainThread - The file [0;37m[4m/Users/rkrivov/Parallels/Windows 10.pvm/parallels.log[4m[0;39m was changed: The size of the remote file ([0;36m[1m8.57 MB[22m[0;39m) differs from the size of the local file ([0;36m[1m8.69 MB[22m[0;39m), and the time when the remote file was last modified ([0;36m[1m2021-08-01 09:06:25[22m[0;39m) differs from the time when the local file was last modified ([0;36m[1m2021-08-02 06:50:23[22m[0;39m), and the ETag of the remote file ([0;36m[1m596b6d3795927861e85b12bb6f1a374c[22m[0;39m) differs from the ETag of the local file ([0;36m[1m0d4d61b14d810e0b53216ff8c6476568[22m[0;39m) in /Users/rkrivov/PycharmProjects/s3_upload/s3/base.py:263
WARNING - 2021-08-02 09:51:39,756 - s3.base - base._compare_files - MainThread - The file [0;37m[4m/Users/rkrivov/Parallels/Windows 10.pvm/harddisk.hdd/harddisk.hdd.0.{5fbaabe3-6958-40ff-92a7-860e329aab41}.hds[4m[0;39m was changed: The size of the remote file ([0;36m[1m2.90 GB[22m[0;39m) differs from the size of the local file ([0;36m[1m10.84 GB[22m[0;39m), and the time when the remote file was last modified ([0;36m[1m2021-08-01 09:10:42[22m[0;39m) differs from the time when the local file was last modified ([0;36m[1m2021-08-02 06:50:23[22m[0;39m), and the ETag of the remote file ([0;36m[1m43c047b7d3f486a9fbb6db51cb0f6f4a[22m[0;39m) differs from the ETag of the local file ([0;36m[1me5037db4b86f843d1a6937ac723ce62a[22m[0;39m) in /Users/rkrivov/PycharmProjects/s3_upload/s3/base.py:263
WARNING - 2021-08-02 10:56:06,301 - __main__ - parallels.main - MainThread - User terminate program! in /Users/rkrivov/PycharmProjects/s3_upload/parallels.py:135
ERROR - 2021-08-02 10:56:08,436 - common.dbase - dbase.execute_update - MainThread - Exception OperationalError with message: near "WHERE": syntax error in /Users/rkrivov/PycharmProjects/s3_upload/common/dbase.py:814
WARNING - 2021-08-02 10:59:22,238 - __main__ - parallels.main - MainThread - User terminate program! in /Users/rkrivov/PycharmProjects/s3_upload/parallels.py:135
CRITICAL - 2021-08-02 14:07:57,243 - __main__ - parallels.main - MainThread - Exception ImportError with message "cannot import name 'S3Object' from partially initialized module 's3._base._object' (most likely due to a circular import) (/Users/rkrivov/PycharmProjects/s3_upload/s3/_base/_object.py)" is not caught in /Users/rkrivov/PycharmProjects/s3_upload/parallels.py:103
Stack (most recent call last):
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/pydevd.py", line 2173, in <module>
    main()
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/pydevd.py", line 2164, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/pydevd.py", line 1476, in run
    return self._exec(is_module, entry_point_fn, module_name, file, globals, locals)
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/pydevd.py", line 1483, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/rkrivov/PycharmProjects/s3_upload/parallels.py", line 115, in <module>
    main()
  File "/Users/rkrivov/PycharmProjects/s3_upload/parallels.py", line 103, in main
    logger.critical(
WARNING - 2021-08-02 14:24:49,483 - __main__ - parallels.main - MainThread - User terminate program! in /Users/rkrivov/PycharmProjects/s3_upload/parallels.py:102
WARNING - 2021-08-02 14:49:45,919 - __main__ - parallels.main - MainThread - User terminate program! in /Users/rkrivov/PycharmProjects/s3_upload/parallels.py:95
WARNING - 2021-08-02 14:52:21,286 - __main__ - parallels.main - MainThread - User terminate program! in /Users/rkrivov/PycharmProjects/s3_upload/parallels.py:95
WARNING - 2021-08-02 14:55:03,123 - __main__ - parallels.main - MainThread - User terminate program! in /Users/rkrivov/PycharmProjects/s3_upload/parallels.py:95
WARNING - 2021-08-02 14:58:41,948 - s3._base._base - _base._compare_files - MainThread - The file [0;37m[4m/Users/rkrivov/Parallels/Windows 10.pvm/config.pvs[4m[0;39m was changed: The size of the remote file ([0;36m[1m33.10 KB[22m[0;39m) differs from the size of the local file ([0;36m[1m33.10 KB[22m[0;39m), and the time when the remote file was last modified ([0;36m[1m2021-08-02 06:52:49[22m[0;39m) differs from the time when the local file was last modified ([0;36m[1m2021-08-02 11:58:21[22m[0;39m), and the ETag of the remote file ([0;36m[1m7809c5caaee28288582c01fa1deb4035[22m[0;39m) differs from the ETag of the local file ([0;36m[1maa3d659a7b294b25dd96895bbed69380[22m[0;39m) in /Users/rkrivov/PycharmProjects/s3_upload/s3/_base/_base.py:269
WARNING - 2021-08-02 14:58:41,962 - s3._base._base - _base._compare_files - MainThread - The file [0;37m[4m/Users/rkrivov/Parallels/Windows 10.pvm/statistic.log[4m[0;39m was changed: The size of the remote file ([0;36m[1m3.70 MB[22m[0;39m) differs from the size of the local file ([0;36m[1m3.70 MB[22m[0;39m), and the time when the remote file was last modified ([0;36m[1m2021-08-02 06:52:49[22m[0;39m) differs from the time when the local file was last modified ([0;36m[1m2021-08-02 11:58:21[22m[0;39m), and the ETag of the remote file ([0;36m[1m9cc3e03874af7fd107dca3e9c270e9b3[22m[0;39m) differs from the ETag of the local file ([0;36m[1mc6306fd9112486c456e6db497fb8d948[22m[0;39m) in /Users/rkrivov/PycharmProjects/s3_upload/s3/_base/_base.py:269
WARNING - 2021-08-02 14:58:41,964 - s3._base._base - _base._compare_files - MainThread - The file [0;37m[4m/Users/rkrivov/Parallels/Windows 10.pvm/config.pvs.backup[4m[0;39m was changed: The size of the remote file ([0;36m[1m33.10 KB[22m[0;39m) differs from the size of the local file ([0;36m[1m33.10 KB[22m[0;39m), and the time when the remote file was last modified ([0;36m[1m2021-08-02 06:52:49[22m[0;39m) differs from the time when the local file was last modified ([0;36m[1m2021-08-02 11:58:21[22m[0;39m), and the ETag of the remote file ([0;36m[1m7809c5caaee28288582c01fa1deb4035[22m[0;39m) differs from the ETag of the local file ([0;36m[1maa3d659a7b294b25dd96895bbed69380[22m[0;39m) in /Users/rkrivov/PycharmProjects/s3_upload/s3/_base/_base.py:269
WARNING - 2021-08-02 14:58:41,997 - s3._base._base - _base._compare_files - MainThread - The file [0;37m[4m/Users/rkrivov/Parallels/Windows 10.pvm/parallels.log[4m[0;39m was changed: The size of the remote file ([0;36m[1m8.69 MB[22m[0;39m) differs from the size of the local file ([0;36m[1m8.96 MB[22m[0;39m), and the time when the remote file was last modified ([0;36m[1m2021-08-02 06:52:50[22m[0;39m) differs from the time when the local file was last modified ([0;36m[1m2021-08-02 11:58:21[22m[0;39m), and the ETag of the remote file ([0;36m[1m0d4d61b14d810e0b53216ff8c6476568[22m[0;39m) differs from the ETag of the local file ([0;36m[1m4f707993e570416e74b0316bda941e53[22m[0;39m) in /Users/rkrivov/PycharmProjects/s3_upload/s3/_base/_base.py:269
WARNING - 2021-08-02 15:03:17,055 - s3._base._base - _base._compare_files - MainThread - The file [0;37m[4m/Users/rkrivov/Parallels/Windows 10.pvm/config.pvs[4m[0;39m was changed: The size of the remote file ([0;36m[1m33.10 KB[22m[0;39m) differs from the size of the local file ([0;36m[1m33.10 KB[22m[0;39m), and the time when the remote file was last modified ([0;36m[1m2021-08-02 06:52:49[22m[0;39m) differs from the time when the local file was last modified ([0;36m[1m2021-08-02 12:03:01[22m[0;39m), and the ETag of the remote file ([0;36m[1m7809c5caaee28288582c01fa1deb4035[22m[0;39m) differs from the ETag of the local file ([0;36m[1m46b693f59fbacab796d01caaf20e34de[22m[0;39m) in /Users/rkrivov/PycharmProjects/s3_upload/s3/_base/_base.py:269
WARNING - 2021-08-02 15:03:17,069 - s3._base._base - _base._compare_files - MainThread - The file [0;37m[4m/Users/rkrivov/Parallels/Windows 10.pvm/statistic.log[4m[0;39m was changed: The size of the remote file ([0;36m[1m3.70 MB[22m[0;39m) differs from the size of the local file ([0;36m[1m3.70 MB[22m[0;39m), and the time when the remote file was last modified ([0;36m[1m2021-08-02 06:52:49[22m[0;39m) differs from the time when the local file was last modified ([0;36m[1m2021-08-02 12:03:01[22m[0;39m), and the ETag of the remote file ([0;36m[1m9cc3e03874af7fd107dca3e9c270e9b3[22m[0;39m) differs from the ETag of the local file ([0;36m[1ma7896af013028936c01564f14c367944[22m[0;39m) in /Users/rkrivov/PycharmProjects/s3_upload/s3/_base/_base.py:269
WARNING - 2021-08-02 15:03:17,071 - s3._base._base - _base._compare_files - MainThread - The file [0;37m[4m/Users/rkrivov/Parallels/Windows 10.pvm/config.pvs.backup[4m[0;39m was changed: The size of the remote file ([0;36m[1m33.10 KB[22m[0;39m) differs from the size of the local file ([0;36m[1m33.10 KB[22m[0;39m), and the time when the remote file was last modified ([0;36m[1m2021-08-02 06:52:49[22m[0;39m) differs from the time when the local file was last modified ([0;36m[1m2021-08-02 12:03:01[22m[0;39m), and the ETag of the remote file ([0;36m[1m7809c5caaee28288582c01fa1deb4035[22m[0;39m) differs from the ETag of the local file ([0;36m[1m46b693f59fbacab796d01caaf20e34de[22m[0;39m) in /Users/rkrivov/PycharmProjects/s3_upload/s3/_base/_base.py:269
WARNING - 2021-08-02 15:03:17,102 - s3._base._base - _base._compare_files - MainThread - The file [0;37m[4m/Users/rkrivov/Parallels/Windows 10.pvm/parallels.log[4m[0;39m was changed: The size of the remote file ([0;36m[1m8.69 MB[22m[0;39m) differs from the size of the local file ([0;36m[1m9.03 MB[22m[0;39m), and the time when the remote file was last modified ([0;36m[1m2021-08-02 06:52:50[22m[0;39m) differs from the time when the local file was last modified ([0;36m[1m2021-08-02 12:03:00[22m[0;39m), and the ETag of the remote file ([0;36m[1m0d4d61b14d810e0b53216ff8c6476568[22m[0;39m) differs from the ETag of the local file ([0;36m[1mc5721203e3fde19be28f9babbe135667[22m[0;39m) in /Users/rkrivov/PycharmProjects/s3_upload/s3/_base/_base.py:269
WARNING - 2021-08-02 15:03:47,332 - s3._base._base - _base._compare_files - MainThread - The file [0;37m[4m/Users/rkrivov/Parallels/Windows 10.pvm/harddisk.hdd/harddisk.hdd.0.{5fbaabe3-6958-40ff-92a7-860e329aab41}.hds[4m[0;39m was changed: The size of the remote file ([0;36m[1m10.84 GB[22m[0;39m) differs from the size of the local file ([0;36m[1m12.05 GB[22m[0;39m), and the time when the remote file was last modified ([0;36m[1m2021-08-02 07:08:48[22m[0;39m) differs from the time when the local file was last modified ([0;36m[1m2021-08-02 12:03:00[22m[0;39m), and the ETag of the remote file ([0;36m[1me5037db4b86f843d1a6937ac723ce62a[22m[0;39m) differs from the ETag of the local file ([0;36m[1mccf6395dd85d4db45f6aa29c35b4db26[22m[0;39m) in /Users/rkrivov/PycharmProjects/s3_upload/s3/_base/_base.py:269
ERROR - 2021-08-02 15:05:19,439 - common.dbase - dbase.execute_update - MainThread - Exception IntegrityError with message: UNIQUE constraint failed: virtual_machines.uuid in /Users/rkrivov/PycharmProjects/s3_upload/common/dbase.py:822
WARNING - 2021-08-02 15:08:00,864 - __main__ - parallels.main - MainThread - User terminate program! in /Users/rkrivov/PycharmProjects/s3_upload/parallels.py:95
ERROR - 2021-08-02 15:08:11,631 - common.dbase - dbase.execute_update - MainThread - Exception IntegrityError with message: UNIQUE constraint failed: virtual_machines.uuid in /Users/rkrivov/PycharmProjects/s3_upload/common/dbase.py:822
ERROR - 2021-08-02 15:10:55,574 - common.dbase - dbase.execute_update - MainThread - Exception IntegrityError with message: UNIQUE constraint failed: virtual_machines.uuid in /Users/rkrivov/PycharmProjects/s3_upload/common/dbase.py:822
WARNING - 2021-08-02 15:17:12,844 - __main__ - parallels.main - MainThread - User terminate program! in /Users/rkrivov/PycharmProjects/s3_upload/parallels.py:95
WARNING - 2021-08-03 01:21:27,465 - __main__ - main.main - MainThread - User terminate program! in /Users/rkrivov/PycharmProjects/s3_upload/main.py:99
WARNING - 2021-08-03 11:37:36,058 - __main__ - main.main - MainThread - User terminate program! in /Users/rkrivov/PycharmProjects/s3_upload/main.py:99
WARNING - 2021-08-03 11:59:07,022 - __main__ - main.main - MainThread - User terminate program! in /Users/rkrivov/PycharmProjects/s3_upload/main.py:99
WARNING - 2021-08-03 11:59:48,874 - __main__ - main.main - MainThread - User terminate program! in /Users/rkrivov/PycharmProjects/s3_upload/main.py:99
WARNING - 2021-08-03 12:00:14,019 - __main__ - main.main - MainThread - User terminate program! in /Users/rkrivov/PycharmProjects/s3_upload/main.py:99
WARNING - 2021-08-03 20:51:29,209 - s3._base._base - _base._compare_files - MainThread - The file [0;37m[4m/Users/rkrivov/Parallels/Windows 10.pvm/Snapshots.xml[4m[0;39m was changed: The size of the remote file ([0;36m[1m1.90 KB[22m[0;39m) differs from the size of the local file ([0;36m[1m2.05 KB[22m[0;39m), and the time when the remote file was last modified ([0;36m[1m2021-07-29 19:43:26[22m[0;39m) differs from the time when the local file was last modified ([0;36m[1m2021-08-03 17:51:23[22m[0;39m), and the ETag of the remote file ([0;36m[1mb230e80f69c8f743ea543beedc351841[22m[0;39m) differs from the ETag of the local file ([0;36m[1m5d50a0235ca4cf452b5f4e40822104dd[22m[0;39m) in /Users/rkrivov/PycharmProjects/s3_upload/s3/_base/_base.py:269
WARNING - 2021-08-03 20:51:29,212 - s3._base._base - _base._compare_files - MainThread - The file [0;37m[4m/Users/rkrivov/Parallels/Windows 10.pvm/harddisk.hdd/harddisk.hdd.{5fbaabe3-6958-40ff-92a7-860e329aab41}.cache[4m[0;39m was changed: The size of the remote file ([0;36m[1m8.40 MB[22m[0;39m) differs from the size of the local file ([0;36m[1m12.30 KB[22m[0;39m), and the time when the remote file was last modified ([0;36m[1m2021-08-01 09:06:26[22m[0;39m) differs from the time when the local file was last modified ([0;36m[1m2021-08-03 17:51:21[22m[0;39m), and the ETag of the remote file ([0;36m[1m339dcbeb4df3065fc1a9fdf11c8d0604[22m[0;39m) differs from the ETag of the local file ([0;36m[1mc7ca1fae53203422a0ebdcc8f57067f4[22m[0;39m) in /Users/rkrivov/PycharmProjects/s3_upload/s3/_base/_base.py:269
WARNING - 2021-08-03 21:03:21,965 - s3._base._base - _base._compare_files - MainThread - The file [0;37m[4m/Users/rkrivov/Parallels/Windows 10.pvm/harddisk.hdd/DiskDescriptor.xml[4m[0;39m was changed: The size of the remote file ([0;36m[1m3.29 KB[22m[0;39m) differs from the size of the local file ([0;36m[1m3.70 KB[22m[0;39m), and the time when the remote file was last modified ([0;36m[1m2021-07-29 19:43:27[22m[0;39m) differs from the time when the local file was last modified ([0;36m[1m2021-08-03 18:03:18[22m[0;39m), and the ETag of the remote file ([0;36m[1mac6eee64a304dedf365c1cf3d1ca712a[22m[0;39m) differs from the ETag of the local file ([0;36m[1mc804ff44d3dcf18954c66c06ecedeaf3[22m[0;39m) in /Users/rkrivov/PycharmProjects/s3_upload/s3/_base/_base.py:269
WARNING - 2021-08-03 21:03:21,969 - s3._base._base - _base._compare_files - MainThread - The file [0;37m[4m/Users/rkrivov/Parallels/Windows 10.pvm/harddisk.hdd/DiskDescriptor.xml.Backup[4m[0;39m was changed: The size of the remote file ([0;36m[1m3.29 KB[22m[0;39m) differs from the size of the local file ([0;36m[1m3.70 KB[22m[0;39m), and the time when the remote file was last modified ([0;36m[1m2021-07-29 19:43:27[22m[0;39m) differs from the time when the local file was last modified ([0;36m[1m2021-08-03 18:03:18[22m[0;39m), and the ETag of the remote file ([0;36m[1mac6eee64a304dedf365c1cf3d1ca712a[22m[0;39m) differs from the ETag of the local file ([0;36m[1mc804ff44d3dcf18954c66c06ecedeaf3[22m[0;39m) in /Users/rkrivov/PycharmProjects/s3_upload/s3/_base/_base.py:269
CRITICAL - 2021-08-03 21:03:35,508 - __main__ - main.main - MainThread - Exception TypeError with message "'>' not supported between instances of 'NoneType' and 'int'" is not caught in /Users/rkrivov/PycharmProjects/s3_upload/main.py:104
Traceback (most recent call last):
  File "/Users/rkrivov/PycharmProjects/s3_upload/main.py", line 95, in main
    CommandDispatch.execute(args.operation,
  File "/Users/rkrivov/PycharmProjects/s3_upload/dispatchers/command_dispatch.py", line 39, in execute
    result = func(*args, **kwargs)
  File "/Users/rkrivov/PycharmProjects/s3_upload/main.py", line 36, in do_backup_vm
    S3ParallelsBackup.execute(*args, **kwargs)
  File "/Users/rkrivov/PycharmProjects/s3_upload/s3/parallels/operation.py", line 490, in execute
    o.process(*args, **kwargs)
  File "/Users/rkrivov/PycharmProjects/s3_upload/s3/parallels/operation.py", line 476, in process
    self._do_run(vm_id=self.vm_uuid)
  File "/Users/rkrivov/PycharmProjects/s3_upload/s3/parallels/operation.py", line 437, in _do_run
    self._run_process(vm_info=vm_info)
  File "/Users/rkrivov/PycharmProjects/s3_upload/s3/parallels/backup.py", line 46, in _run_process
    super(S3ParallelsBackup, self)._run_process(vm_info=vm_info)
  File "/Users/rkrivov/PycharmProjects/s3_upload/s3/parallels/operation.py", line 400, in _run_process
    self._do_operation(files)
  File "/Users/rkrivov/PycharmProjects/s3_upload/s3/parallels/backup.py", line 40, in _do_operation
    self._do_file_operation(local_file_info=local_file, remote_file_info=remote_file)
  File "/Users/rkrivov/PycharmProjects/s3_upload/s3/parallels/backup.py", line 26, in _do_file_operation
    self.storage.upload_file(local_file_path=local_file_name, remote_file_path=remote_file_name)
  File "/Users/rkrivov/PycharmProjects/s3_upload/s3/utils.py", line 21, in wrapper_func
    result = fn(*args, **kwargs)
  File "/Users/rkrivov/PycharmProjects/s3_upload/s3/storage.py", line 405, in upload_file
    self._client.upload_file(
  File "/Users/rkrivov/PycharmProjects/s3_upload/venv/lib/python3.8/site-packages/boto3/s3/inject.py", line 129, in upload_file
    return transfer.upload_file(
  File "/Users/rkrivov/PycharmProjects/s3_upload/venv/lib/python3.8/site-packages/boto3/s3/transfer.py", line 279, in upload_file
    future.result()
  File "/Users/rkrivov/PycharmProjects/s3_upload/venv/lib/python3.8/site-packages/s3transfer/futures.py", line 106, in result
    return self._coordinator.result()
  File "/Users/rkrivov/PycharmProjects/s3_upload/venv/lib/python3.8/site-packages/s3transfer/futures.py", line 265, in result
    raise self._exception
  File "/Users/rkrivov/PycharmProjects/s3_upload/venv/lib/python3.8/site-packages/s3transfer/tasks.py", line 126, in __call__
    return self._execute_main(kwargs)
  File "/Users/rkrivov/PycharmProjects/s3_upload/venv/lib/python3.8/site-packages/s3transfer/tasks.py", line 150, in _execute_main
    return_value = self._main(**kwargs)
  File "/Users/rkrivov/PycharmProjects/s3_upload/venv/lib/python3.8/site-packages/s3transfer/upload.py", line 694, in _main
    client.put_object(Bucket=bucket, Key=key, Body=body, **extra_args)
  File "/Users/rkrivov/PycharmProjects/s3_upload/venv/lib/python3.8/site-packages/s3transfer/utils.py", line 550, in __exit__
    self.close()
  File "/Users/rkrivov/PycharmProjects/s3_upload/venv/lib/python3.8/site-packages/s3transfer/utils.py", line 532, in close
    callback()
  File "/Users/rkrivov/PycharmProjects/s3_upload/venv/lib/python3.8/site-packages/s3transfer/upload.py", line 53, in flush
    self._trigger_callbacks()
  File "/Users/rkrivov/PycharmProjects/s3_upload/venv/lib/python3.8/site-packages/s3transfer/upload.py", line 57, in _trigger_callbacks
    callback(bytes_transferred=self._bytes_seen)
  File "/Users/rkrivov/PycharmProjects/s3_upload/venv/lib/python3.8/site-packages/boto3/s3/transfer.py", line 338, in on_progress
    self._callback(bytes_transferred)
  File "/Users/rkrivov/PycharmProjects/s3_upload/common/progress_bar.py", line 28, in __call__
    iteration = max(0, iteration)
TypeError: '>' not supported between instances of 'NoneType' and 'int'
Stack (most recent call last):
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/pydevd.py", line 2173, in <module>
    main()
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/pydevd.py", line 2164, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/pydevd.py", line 1476, in run
    return self._exec(is_module, entry_point_fn, module_name, file, globals, locals)
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/pydevd.py", line 1483, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/rkrivov/PycharmProjects/s3_upload/main.py", line 119, in <module>
    main()
  File "/Users/rkrivov/PycharmProjects/s3_upload/main.py", line 104, in main
    logger.critical(
CRITICAL - 2021-08-03 21:05:25,390 - __main__ - main.main - MainThread - Exception AttributeError with message "'NoneType' object has no attribute 'get'" is not caught in /Users/rkrivov/PycharmProjects/s3_upload/main.py:104
Traceback (most recent call last):
  File "/Users/rkrivov/PycharmProjects/s3_upload/main.py", line 95, in main
    CommandDispatch.execute(args.operation,
  File "/Users/rkrivov/PycharmProjects/s3_upload/dispatchers/command_dispatch.py", line 39, in execute
    result = func(*args, **kwargs)
  File "/Users/rkrivov/PycharmProjects/s3_upload/main.py", line 36, in do_backup_vm
    S3ParallelsBackup.execute(*args, **kwargs)
  File "/Users/rkrivov/PycharmProjects/s3_upload/s3/parallels/operation.py", line 490, in execute
    o.process(*args, **kwargs)
  File "/Users/rkrivov/PycharmProjects/s3_upload/s3/parallels/operation.py", line 476, in process
    self._do_run(vm_id=self.vm_uuid)
  File "/Users/rkrivov/PycharmProjects/s3_upload/s3/parallels/operation.py", line 437, in _do_run
    self._run_process(vm_info=vm_info)
  File "/Users/rkrivov/PycharmProjects/s3_upload/s3/parallels/backup.py", line 46, in _run_process
    super(S3ParallelsBackup, self)._run_process(vm_info=vm_info)
  File "/Users/rkrivov/PycharmProjects/s3_upload/s3/parallels/operation.py", line 400, in _run_process
    self._do_operation(files)
  File "/Users/rkrivov/PycharmProjects/s3_upload/s3/parallels/backup.py", line 40, in _do_operation
    self._do_file_operation(local_file_info=local_file, remote_file_info=remote_file)
  File "/Users/rkrivov/PycharmProjects/s3_upload/s3/parallels/backup.py", line 24, in _do_file_operation
    remote_file_name = remote_file_info.get('name')
AttributeError: 'NoneType' object has no attribute 'get'
Stack (most recent call last):
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/pydevd.py", line 2173, in <module>
    main()
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/pydevd.py", line 2164, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/pydevd.py", line 1476, in run
    return self._exec(is_module, entry_point_fn, module_name, file, globals, locals)
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/pydevd.py", line 1483, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/rkrivov/PycharmProjects/s3_upload/main.py", line 119, in <module>
    main()
  File "/Users/rkrivov/PycharmProjects/s3_upload/main.py", line 104, in main
    logger.critical(
CRITICAL - 2021-08-03 21:05:39,026 - __main__ - main.main - MainThread - Exception AttributeError with message "'NoneType' object has no attribute 'get'" is not caught in /Users/rkrivov/PycharmProjects/s3_upload/main.py:104
Traceback (most recent call last):
  File "/Users/rkrivov/PycharmProjects/s3_upload/main.py", line 95, in main
    CommandDispatch.execute(args.operation,
  File "/Users/rkrivov/PycharmProjects/s3_upload/dispatchers/command_dispatch.py", line 39, in execute
    result = func(*args, **kwargs)
  File "/Users/rkrivov/PycharmProjects/s3_upload/main.py", line 36, in do_backup_vm
    S3ParallelsBackup.execute(*args, **kwargs)
  File "/Users/rkrivov/PycharmProjects/s3_upload/s3/parallels/operation.py", line 490, in execute
    o.process(*args, **kwargs)
  File "/Users/rkrivov/PycharmProjects/s3_upload/s3/parallels/operation.py", line 476, in process
    self._do_run(vm_id=self.vm_uuid)
  File "/Users/rkrivov/PycharmProjects/s3_upload/s3/parallels/operation.py", line 437, in _do_run
    self._run_process(vm_info=vm_info)
  File "/Users/rkrivov/PycharmProjects/s3_upload/s3/parallels/backup.py", line 46, in _run_process
    super(S3ParallelsBackup, self)._run_process(vm_info=vm_info)
  File "/Users/rkrivov/PycharmProjects/s3_upload/s3/parallels/operation.py", line 400, in _run_process
    self._do_operation(files)
  File "/Users/rkrivov/PycharmProjects/s3_upload/s3/parallels/backup.py", line 40, in _do_operation
    self._do_file_operation(local_file_info=local_file, remote_file_info=remote_file)
  File "/Users/rkrivov/PycharmProjects/s3_upload/s3/parallels/backup.py", line 24, in _do_file_operation
    remote_file_name = remote_file_info.get('name')
AttributeError: 'NoneType' object has no attribute 'get'
Stack (most recent call last):
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/pydevd.py", line 2173, in <module>
    main()
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/pydevd.py", line 2164, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/pydevd.py", line 1476, in run
    return self._exec(is_module, entry_point_fn, module_name, file, globals, locals)
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/pydevd.py", line 1483, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/rkrivov/PycharmProjects/s3_upload/main.py", line 119, in <module>
    main()
  File "/Users/rkrivov/PycharmProjects/s3_upload/main.py", line 104, in main
    logger.critical(
CRITICAL - 2021-08-03 21:05:50,364 - __main__ - main.main - MainThread - Exception AttributeError with message "'NoneType' object has no attribute 'get'" is not caught in /Users/rkrivov/PycharmProjects/s3_upload/main.py:104
Traceback (most recent call last):
  File "/Users/rkrivov/PycharmProjects/s3_upload/main.py", line 95, in main
    CommandDispatch.execute(args.operation,
  File "/Users/rkrivov/PycharmProjects/s3_upload/dispatchers/command_dispatch.py", line 39, in execute
    result = func(*args, **kwargs)
  File "/Users/rkrivov/PycharmProjects/s3_upload/main.py", line 36, in do_backup_vm
    S3ParallelsBackup.execute(*args, **kwargs)
  File "/Users/rkrivov/PycharmProjects/s3_upload/s3/parallels/operation.py", line 490, in execute
    o.process(*args, **kwargs)
  File "/Users/rkrivov/PycharmProjects/s3_upload/s3/parallels/operation.py", line 476, in process
    self._do_run(vm_id=self.vm_uuid)
  File "/Users/rkrivov/PycharmProjects/s3_upload/s3/parallels/operation.py", line 437, in _do_run
    self._run_process(vm_info=vm_info)
  File "/Users/rkrivov/PycharmProjects/s3_upload/s3/parallels/backup.py", line 46, in _run_process
    super(S3ParallelsBackup, self)._run_process(vm_info=vm_info)
  File "/Users/rkrivov/PycharmProjects/s3_upload/s3/parallels/operation.py", line 400, in _run_process
    self._do_operation(files)
  File "/Users/rkrivov/PycharmProjects/s3_upload/s3/parallels/backup.py", line 40, in _do_operation
    self._do_file_operation(local_file_info=local_file, remote_file_info=remote_file)
  File "/Users/rkrivov/PycharmProjects/s3_upload/s3/parallels/backup.py", line 24, in _do_file_operation
    remote_file_name = remote_file_info.get('name')
AttributeError: 'NoneType' object has no attribute 'get'
Stack (most recent call last):
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/pydevd.py", line 2173, in <module>
    main()
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/pydevd.py", line 2164, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/pydevd.py", line 1476, in run
    return self._exec(is_module, entry_point_fn, module_name, file, globals, locals)
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/pydevd.py", line 1483, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/rkrivov/PycharmProjects/s3_upload/main.py", line 118, in <module>
    main()
  File "/Users/rkrivov/PycharmProjects/s3_upload/main.py", line 104, in main
    logger.critical(
WARNING - 2021-08-03 21:10:50,528 - __main__ - main.main - MainThread - User terminate program! in /Users/rkrivov/PycharmProjects/s3_upload/main.py:95
WARNING - 2021-08-03 21:12:21,385 - __main__ - main.main - MainThread - User terminate program! in /Users/rkrivov/PycharmProjects/s3_upload/main.py:95
WARNING - 2021-08-03 21:12:48,934 - __main__ - main.main - MainThread - User terminate program! in /Users/rkrivov/PycharmProjects/s3_upload/main.py:95
WARNING - 2021-08-03 21:17:02,392 - __main__ - main.main - MainThread - User terminate program! in /Users/rkrivov/PycharmProjects/s3_upload/main.py:102
WARNING - 2021-08-03 21:20:47,758 - __main__ - main.main - MainThread - User terminate program! in /Users/rkrivov/PycharmProjects/s3_upload/main.py:95
WARNING - 2021-08-03 22:44:38,464 - __main__ - main.main - MainThread - User terminate program! in /Users/rkrivov/PycharmProjects/s3_upload/main.py:102
WARNING - 2021-08-04 11:27:31,406 - __main__ - main.main - MainThread - User terminate program! in /Users/rkrivov/PycharmProjects/s3_upload/main.py:95
WARNING - 2021-08-04 11:29:52,928 - __main__ - main.main - MainThread - User terminate program! in /Users/rkrivov/PycharmProjects/s3_upload/main.py:95
WARNING - 2021-08-04 11:31:33,777 - __main__ - main.main - MainThread - User terminate program! in /Users/rkrivov/PycharmProjects/s3_upload/main.py:95
WARNING - 2021-08-04 11:38:38,399 - __main__ - main.main - MainThread - User terminate program! in /Users/rkrivov/PycharmProjects/s3_upload/main.py:95
WARNING - 2021-08-04 20:48:37,309 - s3._base._base - _base._compare_files - MainThread - The file [0;37m[4m/Users/rkrivov/Parallels/Windows 10.pvm/VmInfo.pvi[4m[0;39m was changed: The size of the remote file ([0;36m[1m32.43 KB[22m[0;39m) differs from the size of the local file ([0;36m[1m32.44 KB[22m[0;39m), and the time when the remote file was last modified ([0;36m[1m2021-08-03 19:46:22[22m[0;39m) differs from the time when the local file was last modified ([0;36m[1m2021-08-04 09:51:36[22m[0;39m), and the ETag of the remote file ([0;36m[1m2452669023ab7ab0035b80acf4de22fa[22m[0;39m) differs from the ETag of the local file ([0;36m[1mb22f7d7b5e4478382b01ff486d23cf22[22m[0;39m) in /Users/rkrivov/PycharmProjects/s3_upload/s3/_base/_base.py:269
WARNING - 2021-08-04 20:48:37,310 - s3._base._base - _base._compare_files - MainThread - The file [0;37m[4m/Users/rkrivov/Parallels/Windows 10.pvm/suspended.png[4m[0;39m was changed: The size of the remote file ([0;36m[1m210.98 KB[22m[0;39m) differs from the size of the local file ([0;36m[1m126.47 KB[22m[0;39m), and the time when the remote file was last modified ([0;36m[1m2021-08-03 19:46:22[22m[0;39m) differs from the time when the local file was last modified ([0;36m[1m2021-08-04 17:48:33[22m[0;39m), and the ETag of the remote file ([0;36m[1m149a026795591c04a4dde71ebbeb1c63[22m[0;39m) differs from the ETag of the local file ([0;36m[1m4046c87848a6aa5f9886b720b5dd7c7c[22m[0;39m) in /Users/rkrivov/PycharmProjects/s3_upload/s3/_base/_base.py:269
WARNING - 2021-08-04 20:48:37,319 - s3._base._base - _base._compare_files - MainThread - The file [0;37m[4m/Users/rkrivov/Parallels/Windows 10.pvm/config.sav[4m[0;39m was changed: The size of the remote file ([0;36m[1m2.84 MB[22m[0;39m) differs from the size of the local file ([0;36m[1m2.83 MB[22m[0;39m), and the time when the remote file was last modified ([0;36m[1m2021-08-03 19:46:22[22m[0;39m) differs from the time when the local file was last modified ([0;36m[1m2021-08-04 17:48:35[22m[0;39m), and the ETag of the remote file ([0;36m[1md2c6d65748d0ecde26b92d1c454a55d1[22m[0;39m) differs from the ETag of the local file ([0;36m[1mb501b66de6b16f6531bec8b7bae44ca1[22m[0;39m) in /Users/rkrivov/PycharmProjects/s3_upload/s3/_base/_base.py:269
WARNING - 2021-08-04 20:48:37,321 - s3._base._base - _base._compare_files - MainThread - The file [0;37m[4m/Users/rkrivov/Parallels/Windows 10.pvm/config.pvs[4m[0;39m was changed: The size of the remote file ([0;36m[1m33.10 KB[22m[0;39m) differs from the size of the local file ([0;36m[1m33.58 KB[22m[0;39m), and the time when the remote file was last modified ([0;36m[1m2021-08-03 19:46:22[22m[0;39m) differs from the time when the local file was last modified ([0;36m[1m2021-08-04 17:48:33[22m[0;39m), and the ETag of the remote file ([0;36m[1m0292d90859c39a4dacc56a2dbeec1a21[22m[0;39m) differs from the ETag of the local file ([0;36m[1m72002240ed37857ef915a5a273961753[22m[0;39m) in /Users/rkrivov/PycharmProjects/s3_upload/s3/_base/_base.py:269
WARNING - 2021-08-04 20:48:37,334 - s3._base._base - _base._compare_files - MainThread - The file [0;37m[4m/Users/rkrivov/Parallels/Windows 10.pvm/statistic.log[4m[0;39m was changed: The size of the remote file ([0;36m[1m3.72 MB[22m[0;39m) differs from the size of the local file ([0;36m[1m3.73 MB[22m[0;39m), and the time when the remote file was last modified ([0;36m[1m2021-08-03 19:46:23[22m[0;39m) differs from the time when the local file was last modified ([0;36m[1m2021-08-04 17:48:35[22m[0;39m), and the ETag of the remote file ([0;36m[1m8a552ab3d3b96538a3207cddce1fe7ae[22m[0;39m) differs from the ETag of the local file ([0;36m[1m39567aa082598bb8586c1b32fb7c1459[22m[0;39m) in /Users/rkrivov/PycharmProjects/s3_upload/s3/_base/_base.py:269
WARNING - 2021-08-04 20:48:37,335 - s3._base._base - _base._compare_files - MainThread - The file [0;37m[4m/Users/rkrivov/Parallels/Windows 10.pvm/Snapshots.xml[4m[0;39m was changed: The size of the remote file ([0;36m[1m3.31 KB[22m[0;39m) differs from the size of the local file ([0;36m[1m1.35 KB[22m[0;39m), and the time when the remote file was last modified ([0;36m[1m2021-08-03 19:46:23[22m[0;39m) differs from the time when the local file was last modified ([0;36m[1m2021-08-04 17:48:35[22m[0;39m), and the ETag of the remote file ([0;36m[1m822bdde6b102cd0223440566b7575eb2[22m[0;39m) differs from the ETag of the local file ([0;36m[1m58c9f6a932aba6398f9003a1f86ca9be[22m[0;39m) in /Users/rkrivov/PycharmProjects/s3_upload/s3/_base/_base.py:269
WARNING - 2021-08-04 20:48:37,337 - s3._base._base - _base._compare_files - MainThread - The file [0;37m[4m/Users/rkrivov/Parallels/Windows 10.pvm/config.pvs.backup[4m[0;39m was changed: The size of the remote file ([0;36m[1m33.10 KB[22m[0;39m) differs from the size of the local file ([0;36m[1m33.58 KB[22m[0;39m), and the time when the remote file was last modified ([0;36m[1m2021-08-03 19:46:23[22m[0;39m) differs from the time when the local file was last modified ([0;36m[1m2021-08-04 17:48:33[22m[0;39m), and the ETag of the remote file ([0;36m[1m0292d90859c39a4dacc56a2dbeec1a21[22m[0;39m) differs from the ETag of the local file ([0;36m[1m72002240ed37857ef915a5a273961753[22m[0;39m) in /Users/rkrivov/PycharmProjects/s3_upload/s3/_base/_base.py:269
WARNING - 2021-08-04 20:48:37,379 - s3._base._base - _base._compare_files - MainThread - The file [0;37m[4m/Users/rkrivov/Parallels/Windows 10.pvm/parallels.log[4m[0;39m was changed: The size of the remote file ([0;36m[1m10.24 MB[22m[0;39m) differs from the size of the local file ([0;36m[1m10.58 MB[22m[0;39m), and the time when the remote file was last modified ([0;36m[1m2021-08-03 19:46:24[22m[0;39m) differs from the time when the local file was last modified ([0;36m[1m2021-08-04 17:47:25[22m[0;39m), and the ETag of the remote file ([0;36m[1mb4534073a42538bae64fa7012f926aa4[22m[0;39m) differs from the ETag of the local file ([0;36m[1mbfaf219f6d1d5d9376f54bc91be232a1[22m[0;39m) in /Users/rkrivov/PycharmProjects/s3_upload/s3/_base/_base.py:269
WARNING - 2021-08-04 20:48:37,381 - s3._base._base - _base._compare_files - MainThread - The file [0;37m[4m/Users/rkrivov/Parallels/Windows 10.pvm/harddisk.hdd/DiskDescriptor.xml[4m[0;39m was changed: The size of the remote file ([0;36m[1m4.11 KB[22m[0;39m) differs from the size of the local file ([0;36m[1m2.89 KB[22m[0;39m), and the time when the remote file was last modified ([0;36m[1m2021-08-03 20:26:31[22m[0;39m) differs from the time when the local file was last modified ([0;36m[1m2021-08-04 17:48:33[22m[0;39m), and the ETag of the remote file ([0;36m[1m1f8092e23d99e2ae5ce6722aee27272b[22m[0;39m) differs from the ETag of the local file ([0;36m[1m9c0e5ffce5c6226ba8da13d9eefb223b[22m[0;39m) in /Users/rkrivov/PycharmProjects/s3_upload/s3/_base/_base.py:269
WARNING - 2021-08-04 20:48:37,383 - s3._base._base - _base._compare_files - MainThread - The file [0;37m[4m/Users/rkrivov/Parallels/Windows 10.pvm/harddisk.hdd/DiskDescriptor.xml.Backup[4m[0;39m was changed: The size of the remote file ([0;36m[1m4.11 KB[22m[0;39m) differs from the size of the local file ([0;36m[1m2.89 KB[22m[0;39m), and the time when the remote file was last modified ([0;36m[1m2021-08-03 20:26:32[22m[0;39m) differs from the time when the local file was last modified ([0;36m[1m2021-08-04 17:48:33[22m[0;39m), and the ETag of the remote file ([0;36m[1m1f8092e23d99e2ae5ce6722aee27272b[22m[0;39m) differs from the ETag of the local file ([0;36m[1m9c0e5ffce5c6226ba8da13d9eefb223b[22m[0;39m) in /Users/rkrivov/PycharmProjects/s3_upload/s3/_base/_base.py:269
WARNING - 2021-08-04 20:48:37,385 - s3._base._base - _base._compare_files - MainThread - The file [0;37m[4m/Users/rkrivov/Parallels/Windows 10.pvm/harddisk.hdd/harddisk.hdd.drh[4m[0;39m was changed: The size of the remote file ([0;36m[1m3.18 KB[22m[0;39m) differs from the size of the local file ([0;36m[1m21.39 KB[22m[0;39m), and the time when the remote file was last modified ([0;36m[1m2021-08-03 20:45:56[22m[0;39m) differs from the time when the local file was last modified ([0;36m[1m2021-08-04 09:51:05[22m[0;39m), and the ETag of the remote file ([0;36m[1m95b0a6a46ee22c6fdd9bfef021d8f10a[22m[0;39m) differs from the ETag of the local file ([0;36m[1m18ef817c83ca00f99105f6235beddf6b[22m[0;39m) in /Users/rkrivov/PycharmProjects/s3_upload/s3/_base/_base.py:269
WARNING - 2021-08-04 20:49:28,458 - s3._base._base - _base._compare_files - MainThread - The file [0;37m[4m/Users/rkrivov/Parallels/Windows 10.pvm/VmInfo.pvi[4m[0;39m was changed: The size of the remote file ([0;36m[1m32.44 KB[22m[0;39m) differs from the size of the local file ([0;36m[1m32.43 KB[22m[0;39m), and the time when the remote file was last modified ([0;36m[1m2021-08-04 17:48:41[22m[0;39m) differs from the time when the local file was last modified ([0;36m[1m2021-08-04 17:49:01[22m[0;39m), and the ETag of the remote file ([0;36m[1mb22f7d7b5e4478382b01ff486d23cf22[22m[0;39m) differs from the ETag of the local file ([0;36m[1m52fddf5f9b2786fbfeff0e70ac7724eb[22m[0;39m) in /Users/rkrivov/PycharmProjects/s3_upload/s3/_base/_base.py:269
WARNING - 2021-08-04 20:49:28,460 - s3._base._base - _base._compare_files - MainThread - The file [0;37m[4m/Users/rkrivov/Parallels/Windows 10.pvm/suspended.png[4m[0;39m was changed: The size of the remote file ([0;36m[1m126.47 KB[22m[0;39m) differs from the size of the local file ([0;36m[1m127.37 KB[22m[0;39m), and the time when the remote file was last modified ([0;36m[1m2021-08-04 17:48:41[22m[0;39m) differs from the time when the local file was last modified ([0;36m[1m2021-08-04 17:49:25[22m[0;39m), and the ETag of the remote file ([0;36m[1m4046c87848a6aa5f9886b720b5dd7c7c[22m[0;39m) differs from the ETag of the local file ([0;36m[1m4dc058d318ac50c7f42370d64b08a001[22m[0;39m) in /Users/rkrivov/PycharmProjects/s3_upload/s3/_base/_base.py:269
WARNING - 2021-08-04 20:49:28,471 - s3._base._base - _base._compare_files - MainThread - The file [0;37m[4m/Users/rkrivov/Parallels/Windows 10.pvm/config.sav[4m[0;39m was changed: The size of the remote file ([0;36m[1m2.83 MB[22m[0;39m) differs from the size of the local file ([0;36m[1m2.85 MB[22m[0;39m), and the time when the remote file was last modified ([0;36m[1m2021-08-04 17:48:41[22m[0;39m) differs from the time when the local file was last modified ([0;36m[1m2021-08-04 17:49:25[22m[0;39m), and the ETag of the remote file ([0;36m[1mb501b66de6b16f6531bec8b7bae44ca1[22m[0;39m) differs from the ETag of the local file ([0;36m[1mc7f86050e5208768c5c32ab3543ec4be[22m[0;39m) in /Users/rkrivov/PycharmProjects/s3_upload/s3/_base/_base.py:269
WARNING - 2021-08-04 20:49:28,487 - s3._base._base - _base._compare_files - MainThread - The file [0;37m[4m/Users/rkrivov/Parallels/Windows 10.pvm/statistic.log[4m[0;39m was changed: The size of the remote file ([0;36m[1m3.73 MB[22m[0;39m) differs from the size of the local file ([0;36m[1m3.73 MB[22m[0;39m), and the time when the remote file was last modified ([0;36m[1m2021-08-04 17:48:43[22m[0;39m) differs from the time when the local file was last modified ([0;36m[1m2021-08-04 17:49:27[22m[0;39m), and the ETag of the remote file ([0;36m[1m39567aa082598bb8586c1b32fb7c1459[22m[0;39m) differs from the ETag of the local file ([0;36m[1m82c6a82fe4788f67af747a756b6f3dc6[22m[0;39m) in /Users/rkrivov/PycharmProjects/s3_upload/s3/_base/_base.py:269
WARNING - 2021-08-04 20:49:28,528 - s3._base._base - _base._compare_files - MainThread - The file [0;37m[4m/Users/rkrivov/Parallels/Windows 10.pvm/parallels.log[4m[0;39m was changed: The size of the remote file ([0;36m[1m10.58 MB[22m[0;39m) differs from the size of the local file ([0;36m[1m10.64 MB[22m[0;39m), and the time when the remote file was last modified ([0;36m[1m2021-08-04 17:48:45[22m[0;39m) differs from the time when the local file was last modified ([0;36m[1m2021-08-04 17:49:27[22m[0;39m), and the ETag of the remote file ([0;36m[1mbfaf219f6d1d5d9376f54bc91be232a1[22m[0;39m) differs from the ETag of the local file ([0;36m[1md90aa8355f7b586218cca36701f64dc8[22m[0;39m) in /Users/rkrivov/PycharmProjects/s3_upload/s3/_base/_base.py:269
WARNING - 2021-08-04 20:49:28,555 - s3._base._base - _base._compare_files - MainThread - The file [0;37m[4m/Users/rkrivov/Parallels/Windows 10.pvm/harddisk.hdd/harddisk.hdd.{5fbaabe3-6958-40ff-92a7-860e329aab41}.cache[4m[0;39m was changed: The size of the remote file ([0;36m[1m12.30 KB[22m[0;39m) differs from the size of the local file ([0;36m[1m8.27 MB[22m[0;39m), and the time when the remote file was last modified ([0;36m[1m2021-08-03 20:26:30[22m[0;39m) differs from the time when the local file was last modified ([0;36m[1m2021-08-04 17:49:26[22m[0;39m), and the ETag of the remote file ([0;36m[1mf59477f0a5b64a7470cf24aa57351316[22m[0;39m) differs from the ETag of the local file ([0;36m[1m12231318a29469e396a823d3aa0c3e9c[22m[0;39m) in /Users/rkrivov/PycharmProjects/s3_upload/s3/_base/_base.py:269
WARNING - 2021-08-04 20:49:29,533 - s3._base._base - _base._compare_files - MainThread - The file [0;37m[4m/Users/rkrivov/Parallels/Windows 10.pvm/harddisk.hdd/harddisk.hdd.0.{5fbaabe3-6958-40ff-92a7-860e329aab41}.hds[4m[0;39m was changed: The size of the remote file ([0;36m[1m2.10 MB[22m[0;39m) differs from the size of the local file ([0;36m[1m370.15 MB[22m[0;39m), and the time when the remote file was last modified ([0;36m[1m2021-08-03 20:26:32[22m[0;39m) differs from the time when the local file was last modified ([0;36m[1m2021-08-04 17:49:26[22m[0;39m), and the ETag of the remote file ([0;36m[1ma721752be3dbbdcbadc7c28a0b770a29[22m[0;39m) differs from the ETag of the local file ([0;36m[1m56d34fd001b70870ce27b04c72f5b848[22m[0;39m) in /Users/rkrivov/PycharmProjects/s3_upload/s3/_base/_base.py:269
WARNING - 2021-08-04 20:51:33,463 - s3._base._base - _base._compare_files - MainThread - The file [0;37m[4m/Users/rkrivov/Parallels/Windows 10.pvm/suspended.png[4m[0;39m was changed: The size of the remote file ([0;36m[1m127.37 KB[22m[0;39m) differs from the size of the local file ([0;36m[1m127.71 KB[22m[0;39m), and the time when the remote file was last modified ([0;36m[1m2021-08-04 17:49:40[22m[0;39m) differs from the time when the local file was last modified ([0;36m[1m2021-08-04 17:51:30[22m[0;39m), and the ETag of the remote file ([0;36m[1m4dc058d318ac50c7f42370d64b08a001[22m[0;39m) differs from the ETag of the local file ([0;36m[1m86ca824fecf47e37e69b72591666b9ce[22m[0;39m) in /Users/rkrivov/PycharmProjects/s3_upload/s3/_base/_base.py:269
WARNING - 2021-08-04 20:51:33,472 - s3._base._base - _base._compare_files - MainThread - The file [0;37m[4m/Users/rkrivov/Parallels/Windows 10.pvm/config.sav[4m[0;39m was changed: The size of the remote file ([0;36m[1m2.85 MB[22m[0;39m) differs from the size of the local file ([0;36m[1m2.85 MB[22m[0;39m), and the time when the remote file was last modified ([0;36m[1m2021-08-04 17:49:41[22m[0;39m) differs from the time when the local file was last modified ([0;36m[1m2021-08-04 17:51:30[22m[0;39m), and the ETag of the remote file ([0;36m[1mc7f86050e5208768c5c32ab3543ec4be[22m[0;39m) differs from the ETag of the local file ([0;36m[1m84b4e86d4f5a110b0dcc363b51a14f69[22m[0;39m) in /Users/rkrivov/PycharmProjects/s3_upload/s3/_base/_base.py:269
WARNING - 2021-08-04 20:51:33,484 - s3._base._base - _base._compare_files - MainThread - The file [0;37m[4m/Users/rkrivov/Parallels/Windows 10.pvm/statistic.log[4m[0;39m was changed: The size of the remote file ([0;36m[1m3.73 MB[22m[0;39m) differs from the size of the local file ([0;36m[1m3.73 MB[22m[0;39m), and the time when the remote file was last modified ([0;36m[1m2021-08-04 17:49:43[22m[0;39m) differs from the time when the local file was last modified ([0;36m[1m2021-08-04 17:51:32[22m[0;39m), and the ETag of the remote file ([0;36m[1m82c6a82fe4788f67af747a756b6f3dc6[22m[0;39m) differs from the ETag of the local file ([0;36m[1m361f6a08f4d868ce53e1e3bb516edbe8[22m[0;39m) in /Users/rkrivov/PycharmProjects/s3_upload/s3/_base/_base.py:269
WARNING - 2021-08-04 20:51:33,518 - s3._base._base - _base._compare_files - MainThread - The file [0;37m[4m/Users/rkrivov/Parallels/Windows 10.pvm/parallels.log[4m[0;39m was changed: The size of the remote file ([0;36m[1m10.64 MB[22m[0;39m) differs from the size of the local file ([0;36m[1m10.71 MB[22m[0;39m), and the time when the remote file was last modified ([0;36m[1m2021-08-04 17:49:45[22m[0;39m) differs from the time when the local file was last modified ([0;36m[1m2021-08-04 17:51:31[22m[0;39m), and the ETag of the remote file ([0;36m[1md90aa8355f7b586218cca36701f64dc8[22m[0;39m) differs from the ETag of the local file ([0;36m[1m549eb70a07a3dc1c8251db170cc56cd1[22m[0;39m) in /Users/rkrivov/PycharmProjects/s3_upload/s3/_base/_base.py:269
WARNING - 2021-08-04 20:51:35,014 - s3._base._base - _base._compare_files - MainThread - The file [0;37m[4m/Users/rkrivov/Parallels/Windows 10.pvm/harddisk.hdd/harddisk.hdd.0.{5fbaabe3-6958-40ff-92a7-860e329aab41}.hds[4m[0;39m was changed: The size of the remote file ([0;36m[1m370.15 MB[22m[0;39m) differs from the size of the local file ([0;36m[1m602.93 MB[22m[0;39m), and the time when the remote file was last modified ([0;36m[1m2021-08-04 17:50:35[22m[0;39m) differs from the time when the local file was last modified ([0;36m[1m2021-08-04 17:51:31[22m[0;39m), and the ETag of the remote file ([0;36m[1m56d34fd001b70870ce27b04c72f5b848[22m[0;39m) differs from the ETag of the local file ([0;36m[1ma42a1b99151f5cc729f36ccaecb5c8da[22m[0;39m) in /Users/rkrivov/PycharmProjects/s3_upload/s3/_base/_base.py:269
WARNING - 2021-08-04 20:58:57,231 - s3._base._base - _base._compare_files - MainThread - The file [0;37m[4m/Users/rkrivov/Parallels/Windows 10.pvm/suspended.png[4m[0;39m was changed: The size of the remote file ([0;36m[1m127.71 KB[22m[0;39m) differs from the size of the local file ([0;36m[1m130.31 KB[22m[0;39m), and the time when the remote file was last modified ([0;36m[1m2021-08-04 17:51:42[22m[0;39m) differs from the time when the local file was last modified ([0;36m[1m2021-08-04 17:58:19[22m[0;39m), and the ETag of the remote file ([0;36m[1m86ca824fecf47e37e69b72591666b9ce[22m[0;39m) differs from the ETag of the local file ([0;36m[1mfdd9d55776e4d2006eee16c3561ea9ba[22m[0;39m) in /Users/rkrivov/PycharmProjects/s3_upload/s3/_base/_base.py:269
WARNING - 2021-08-04 21:03:53,043 - s3._base._base - _base._compare_files - MainThread - The file [0;37m[4m/Users/rkrivov/Parallels/Windows 10.pvm/VmInfo.pvi[4m[0;39m was changed: The size of the remote file ([0;36m[1m32.43 KB[22m[0;39m) differs from the size of the local file ([0;36m[1m33.17 KB[22m[0;39m), and the time when the remote file was last modified ([0;36m[1m2021-08-04 17:49:37[22m[0;39m) differs from the time when the local file was last modified ([0;36m[1m2021-08-04 18:03:35[22m[0;39m), and the ETag of the remote file ([0;36m[1m52fddf5f9b2786fbfeff0e70ac7724eb[22m[0;39m) differs from the ETag of the local file ([0;36m[1mc038f31d9094343119e95f3893315b7c[22m[0;39m) in /Users/rkrivov/PycharmProjects/s3_upload/s3/_base/_base.py:269
WARNING - 2021-08-04 21:04:01,117 - s3._base._base - _base._compare_files - MainThread - The file [0;37m[4m/Users/rkrivov/Parallels/Windows 10.pvm/statistic.log[4m[0;39m was changed: The size of the remote file ([0;36m[1m3.73 MB[22m[0;39m) differs from the size of the local file ([0;36m[1m3.73 MB[22m[0;39m), and the time when the remote file was last modified ([0;36m[1m2021-08-04 17:51:49[22m[0;39m) differs from the time when the local file was last modified ([0;36m[1m2021-08-04 18:03:37[22m[0;39m), and the ETag of the remote file ([0;36m[1m361f6a08f4d868ce53e1e3bb516edbe8[22m[0;39m) differs from the ETag of the local file ([0;36m[1m14a5a82ae26d6ea1de69fed791b3e967[22m[0;39m) in /Users/rkrivov/PycharmProjects/s3_upload/s3/_base/_base.py:269
WARNING - 2021-08-04 21:04:03,300 - s3._base._base - _base._compare_files - MainThread - The file [0;37m[4m/Users/rkrivov/Parallels/Windows 10.pvm/parallels.log[4m[0;39m was changed: The size of the remote file ([0;36m[1m10.71 MB[22m[0;39m) differs from the size of the local file ([0;36m[1m10.84 MB[22m[0;39m), and the time when the remote file was last modified ([0;36m[1m2021-08-04 17:51:57[22m[0;39m) differs from the time when the local file was last modified ([0;36m[1m2021-08-04 18:03:36[22m[0;39m), and the ETag of the remote file ([0;36m[1m549eb70a07a3dc1c8251db170cc56cd1[22m[0;39m) differs from the ETag of the local file ([0;36m[1m72150563651c84ac6c48a6a0c8345951[22m[0;39m) in /Users/rkrivov/PycharmProjects/s3_upload/s3/_base/_base.py:269
WARNING - 2021-08-04 21:04:09,564 - s3._base._base - _base._compare_files - MainThread - The file [0;37m[4m/Users/rkrivov/Parallels/Windows 10.pvm/harddisk.hdd/harddisk.hdd.{5fbaabe3-6958-40ff-92a7-860e329aab41}.cache[4m[0;39m was changed: The size of the remote file ([0;36m[1m8.27 MB[22m[0;39m) differs from the size of the local file ([0;36m[1m8.40 MB[22m[0;39m), and the time when the remote file was last modified ([0;36m[1m2021-08-04 17:49:47[22m[0;39m) differs from the time when the local file was last modified ([0;36m[1m2021-08-04 18:03:36[22m[0;39m), and the ETag of the remote file ([0;36m[1m12231318a29469e396a823d3aa0c3e9c[22m[0;39m) differs from the ETag of the local file ([0;36m[1m7c978e68773e4fdf61fc16bb76556780[22m[0;39m) in /Users/rkrivov/PycharmProjects/s3_upload/s3/_base/_base.py:269
WARNING - 2021-08-04 21:04:15,029 - s3._base._base - _base._compare_files - MainThread - The file [0;37m[4m/Users/rkrivov/Parallels/Windows 10.pvm/harddisk.hdd/harddisk.hdd.0.{5fbaabe3-6958-40ff-92a7-860e329aab41}.hds[4m[0;39m was changed: The size of the remote file ([0;36m[1m602.93 MB[22m[0;39m) differs from the size of the local file ([0;36m[1m2.23 GB[22m[0;39m), and the time when the remote file was last modified ([0;36m[1m2021-08-04 17:56:19[22m[0;39m) differs from the time when the local file was last modified ([0;36m[1m2021-08-04 18:03:36[22m[0;39m), and the ETag of the remote file ([0;36m[1ma42a1b99151f5cc729f36ccaecb5c8da[22m[0;39m) differs from the ETag of the local file ([0;36m[1m9e7aed284f48b80cca9ee360aaac6482[22m[0;39m) in /Users/rkrivov/PycharmProjects/s3_upload/s3/_base/_base.py:269
WARNING - 2021-08-04 21:10:55,184 - s3._base._base - _base._compare_files - MainThread - The file [0;37m[4m/Users/rkrivov/Parallels/Windows 10.pvm/VmInfo.pvi[4m[0;39m was changed: The size of the remote file ([0;36m[1m33.17 KB[22m[0;39m) differs from the size of the local file ([0;36m[1m33.17 KB[22m[0;39m), and the time when the remote file was last modified ([0;36m[1m2021-08-04 18:04:37[22m[0;39m) differs from the time when the local file was last modified ([0;36m[1m2021-08-04 18:10:52[22m[0;39m), and the ETag of the remote file ([0;36m[1mc038f31d9094343119e95f3893315b7c[22m[0;39m) differs from the ETag of the local file ([0;36m[1m0d57b5ab26d0820f36e7575795ce05af[22m[0;39m) in /Users/rkrivov/PycharmProjects/s3_upload/s3/_base/_base.py:269
WARNING - 2021-08-04 21:10:55,198 - s3._base._base - _base._compare_files - MainThread - The file [0;37m[4m/Users/rkrivov/Parallels/Windows 10.pvm/statistic.log[4m[0;39m was changed: The size of the remote file ([0;36m[1m3.73 MB[22m[0;39m) differs from the size of the local file ([0;36m[1m3.73 MB[22m[0;39m), and the time when the remote file was last modified ([0;36m[1m2021-08-04 18:04:37[22m[0;39m) differs from the time when the local file was last modified ([0;36m[1m2021-08-04 18:10:54[22m[0;39m), and the ETag of the remote file ([0;36m[1m14a5a82ae26d6ea1de69fed791b3e967[22m[0;39m) differs from the ETag of the local file ([0;36m[1m4eaa44e800ce644118ed2ede188c8417[22m[0;39m) in /Users/rkrivov/PycharmProjects/s3_upload/s3/_base/_base.py:269
WARNING - 2021-08-04 21:10:55,235 - s3._base._base - _base._compare_files - MainThread - The file [0;37m[4m/Users/rkrivov/Parallels/Windows 10.pvm/parallels.log[4m[0;39m was changed: The size of the remote file ([0;36m[1m10.84 MB[22m[0;39m) differs from the size of the local file ([0;36m[1m10.89 MB[22m[0;39m), and the time when the remote file was last modified ([0;36m[1m2021-08-04 18:04:38[22m[0;39m) differs from the time when the local file was last modified ([0;36m[1m2021-08-04 18:10:53[22m[0;39m), and the ETag of the remote file ([0;36m[1m72150563651c84ac6c48a6a0c8345951[22m[0;39m) differs from the ETag of the local file ([0;36m[1m279550fe99585323a0bd97eaf898d12b[22m[0;39m) in /Users/rkrivov/PycharmProjects/s3_upload/s3/_base/_base.py:269
WARNING - 2021-08-04 21:11:01,161 - s3._base._base - _base._compare_files - MainThread - The file [0;37m[4m/Users/rkrivov/Parallels/Windows 10.pvm/harddisk.hdd/harddisk.hdd.0.{5fbaabe3-6958-40ff-92a7-860e329aab41}.hds[4m[0;39m was changed: The size of the remote file ([0;36m[1m2.23 GB[22m[0;39m) differs from the size of the local file ([0;36m[1m2.82 GB[22m[0;39m), and the time when the remote file was last modified ([0;36m[1m2021-08-04 18:07:56[22m[0;39m) differs from the time when the local file was last modified ([0;36m[1m2021-08-04 18:10:53[22m[0;39m), and the ETag of the remote file ([0;36m[1m9e7aed284f48b80cca9ee360aaac6482[22m[0;39m) differs from the ETag of the local file ([0;36m[1m0f4be7dc6d33b6629e68656d82257f15[22m[0;39m) in /Users/rkrivov/PycharmProjects/s3_upload/s3/_base/_base.py:269
WARNING - 2021-08-04 21:11:01,163 - s3._base._base - _base._compare_files - MainThread - The file [0;37m[4m/Users/rkrivov/Parallels/Windows 10.pvm/harddisk.hdd/harddisk.hdd.drh[4m[0;39m was changed: The size of the remote file ([0;36m[1m21.39 KB[22m[0;39m) differs from the size of the local file ([0;36m[1m3.58 KB[22m[0;39m), and the time when the remote file was last modified ([0;36m[1m2021-08-04 17:48:45[22m[0;39m) differs from the time when the local file was last modified ([0;36m[1m2021-08-04 18:08:37[22m[0;39m), and the ETag of the remote file ([0;36m[1m18ef817c83ca00f99105f6235beddf6b[22m[0;39m) differs from the ETag of the local file ([0;36m[1m056f6e32c3c31c151e4ebeeb3f459cea[22m[0;39m) in /Users/rkrivov/PycharmProjects/s3_upload/s3/_base/_base.py:269
WARNING - 2021-08-04 23:50:51,533 - s3._base._base - _base._compare_files - MainThread - The file [0;37m[4m/Users/rkrivov/Parallels/Windows 10.pvm/VmInfo.pvi[4m[0;39m was changed: The size of the remote file ([0;36m[1m33.17 KB[22m[0;39m) differs from the size of the local file ([0;36m[1m33.17 KB[22m[0;39m), and the time when the remote file was last modified ([0;36m[1m2021-08-04 18:11:02[22m[0;39m) differs from the time when the local file was last modified ([0;36m[1m2021-08-04 20:00:41[22m[0;39m), and the ETag of the remote file ([0;36m[1m0d57b5ab26d0820f36e7575795ce05af[22m[0;39m) differs from the ETag of the local file ([0;36m[1mac080707d3166b16879df6ba4f22d318[22m[0;39m) in /Users/rkrivov/PycharmProjects/s3_upload/s3/_base/_base.py:269
WARNING - 2021-08-04 23:50:51,548 - s3._base._base - _base._compare_files - MainThread - The file [0;37m[4m/Users/rkrivov/Parallels/Windows 10.pvm/statistic.log[4m[0;39m was changed: The size of the remote file ([0;36m[1m3.73 MB[22m[0;39m) differs from the size of the local file ([0;36m[1m3.73 MB[22m[0;39m), and the time when the remote file was last modified ([0;36m[1m2021-08-04 18:11:03[22m[0;39m) differs from the time when the local file was last modified ([0;36m[1m2021-08-04 20:00:43[22m[0;39m), and the ETag of the remote file ([0;36m[1m4eaa44e800ce644118ed2ede188c8417[22m[0;39m) differs from the ETag of the local file ([0;36m[1m72bea41c7d03d19ee96b8b3df9782e4c[22m[0;39m) in /Users/rkrivov/PycharmProjects/s3_upload/s3/_base/_base.py:269
WARNING - 2021-08-04 23:50:51,589 - s3._base._base - _base._compare_files - MainThread - The file [0;37m[4m/Users/rkrivov/Parallels/Windows 10.pvm/parallels.log[4m[0;39m was changed: The size of the remote file ([0;36m[1m10.89 MB[22m[0;39m) differs from the size of the local file ([0;36m[1m10.95 MB[22m[0;39m), and the time when the remote file was last modified ([0;36m[1m2021-08-04 18:11:04[22m[0;39m) differs from the time when the local file was last modified ([0;36m[1m2021-08-04 20:00:42[22m[0;39m), and the ETag of the remote file ([0;36m[1m279550fe99585323a0bd97eaf898d12b[22m[0;39m) differs from the ETag of the local file ([0;36m[1m52e419c6122bc103d1cd725081d9f399[22m[0;39m) in /Users/rkrivov/PycharmProjects/s3_upload/s3/_base/_base.py:269
WARNING - 2021-08-04 23:51:03,013 - s3._base._base - _base._compare_files - MainThread - The file [0;37m[4m/Users/rkrivov/Parallels/Windows 10.pvm/harddisk.hdd/harddisk.hdd.0.{5fbaabe3-6958-40ff-92a7-860e329aab41}.hds[4m[0;39m was changed: The size of the remote file ([0;36m[1m2.82 GB[22m[0;39m) differs from the size of the local file ([0;36m[1m4.24 GB[22m[0;39m), and the time when the remote file was last modified ([0;36m[1m2021-08-04 18:18:03[22m[0;39m) differs from the time when the local file was last modified ([0;36m[1m2021-08-04 20:00:42[22m[0;39m), and the ETag of the remote file ([0;36m[1m0f4be7dc6d33b6629e68656d82257f15[22m[0;39m) differs from the ETag of the local file ([0;36m[1mbef2fa4aab3ba58d6e44f1099dd34362[22m[0;39m) in /Users/rkrivov/PycharmProjects/s3_upload/s3/_base/_base.py:269
WARNING - 2021-08-04 23:51:03,017 - s3._base._base - _base._compare_files - MainThread - The file [0;37m[4m/Users/rkrivov/Parallels/Windows 10.pvm/harddisk.hdd/harddisk.hdd.drh[4m[0;39m was changed: The size of the remote file ([0;36m[1m3.58 KB[22m[0;39m) differs from the size of the local file ([0;36m[1m3.18 KB[22m[0;39m), and the time when the remote file was last modified ([0;36m[1m2021-08-04 18:18:03[22m[0;39m) differs from the time when the local file was last modified ([0;36m[1m2021-08-04 18:18:13[22m[0;39m), and the ETag of the remote file ([0;36m[1m056f6e32c3c31c151e4ebeeb3f459cea[22m[0;39m) differs from the ETag of the local file ([0;36m[1m9e92cb9f4a0bbccefd6900a588225c7f[22m[0;39m) in /Users/rkrivov/PycharmProjects/s3_upload/s3/_base/_base.py:269
WARNING - 2021-08-05 00:56:13,877 - __main__ - main.main - MainThread - User terminate program! in /Users/rkrivov/PycharmProjects/s3_upload/main.py:95
WARNING - 2021-08-05 00:59:51,098 - __main__ - main.main - MainThread - User terminate program! in /Users/rkrivov/PycharmProjects/s3_upload/main.py:95
ERROR - 2021-08-05 01:11:55,984 - s3.parallels.parallels - parallels.__init__ - MainThread - Command failed with code: 1 [which prlctl23] in /Users/rkrivov/PycharmProjects/s3_upload/s3/parallels/parallels.py:38
